### PR TITLE
Fix: handle scipy failures due to renaming of scipy.sparse modules in v1.8

### LINKED ISSUE #5: Failing tests: slicing sparse matrices
The tests currently fail due to issues slicing scipy sparse matrices.

I believe the issue is here, where slicer looks up the maximum dimension of an object:

https://github.com/interpretml/slicer/blob/683fd5c5e7ee28fc5abb6d3d5bd8b41235352d92/slicer/slicer_internal.py#L593-L597

Scipy sparse matrices are identified by their `.__class__.__module__` and `.__class__.__name__`, in this lookup table:

https://github.com/interpretml/slicer/blob/683fd5c5e7ee28fc5abb6d3d5bd8b41235352d92/slicer/slicer_internal.py#L568-L569

However, scipy sparse matrices currently seems to live in the module `scipy.sparse._csc`, not `scipy.sparse.csc` . So, the objects are given a maximum dimension of 0, leading to an `IndexError`.

### PR DESCRIPTION
**Pull request by connortann**
Fixes the unit tests, and closes #5 

Changes:
- Handle renaming of scipy.sparse submodules in scipy v1.8
- Slightly more verbose stderr in tests

After this change is in, it would be great to have a release if possible.

### CODE REVIEW

**Comment by paulbkoch** [comment]
Thanks @connortann -- I'll put out a release out with this.

**Comment by paulbkoch** [comment]
v0.0.8 released on PyPI now.

**Comment by connortann** [comment]
@paulbkoch that's great! Would you be able to make a release on conda-forge as well?

I noticed on the [feedstock repo](https://github.com/conda-forge/slicer-feedstock) there no auto-update Pull Request. On the current migrations page, it looks like the update to v0.0.8 has hit an error:

https://conda-forge.org/status/#current_migrations

```
2.00 attempts - The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '0.0.8' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slicer-{{ version }}.tar.gz'
```

**Comment by paulbkoch** [comment]
I'm not an owner of the feedstock repo.  I think only Scott is, last I looked.

If you end up getting access, can you also add me as a maintainer of the feedstock in case we take a dependency on slicer in the future for InterpretML.

**Comment by paulbkoch** [comment]
You know what, I'll ping Scott and ask him.

**Comment by paulbkoch** [comment]
Pinged Scott and asked him to add both of us @connortann as maintainers of the slicer feedstock.

**Comment by paulbkoch** [comment]
Hi @connortann -- We're both maintainers for the slicer feedstock now.  Do you want to take up the release from there?

**Comment by connortann** [comment]
Thanks! I'll take a look. I'm admittedly not particularly experienced with conda feedstocks but shall have a go getting the recipe updated.

Talking of maintainers, please do let me know if you'd be interested in becoming a maintainer of shap: https://github.com/shap/shap/discussions/3559

**Comment by paulbkoch** [comment]
Ok, I'll put out a release then.  It's kind of a weird system that conda-forge uses, but I'm familiar with it.

**Comment by paulbkoch** [comment]
Thanks @connortann -- I think I'll pass on being a shap maintainer for now, but I'll let you know if anything changes in the future.  I've got my hands pretty full at the moment since I'm still maintaining the interpret repo, and have more recently become involved in Scott's new Guidance project https://github.com/guidance-ai/guidance/

**Comment by paulbkoch** [comment]
Hi @connortann -- Slicer v0.0.8 is on conda-forge.

**Pull request merged**
